# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ps_clock_led_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_clock_led_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_clock_led_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ps_clock_led_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_clock_led_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_clock_led_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
