# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/fastAcess/recent/xen_on_ARM/PR/ps_clock_test/ps_clock_test/ps_clock_test.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
