# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led.xdc

# Block Designs: bd/ps_clock_led/ps_clock_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_clock_led || ORIG_REF_NAME==ps_clock_led}]

# IP: bd/ps_clock_led/ip/ps_clock_led_zynq_ultra_ps_e_0_0/ps_clock_led_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_clock_led_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_clock_led_zynq_ultra_ps_e_0_0}]

# IP: bd/ps_clock_led/ip/ps_clock_led_led_0_0/ps_clock_led_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_clock_led_led_0_0 || ORIG_REF_NAME==ps_clock_led_led_0_0}]

# XDC: bd/ps_clock_led/ps_clock_led_ooc.xdc
